# Codecov Configuration
# Story: 0-17 Test Reporting Dashboard
# AC: 5 - Coverage trends (line, branch, function)
# AC: 9 - Coverage threshold 80% enforced

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 2%
    patch:
      default:
        target: 80%

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: true

flags:
  unit:
    paths:
      - api/
      - web/
    carryforward: true
  integration:
    paths:
      - api/
    carryforward: true
